### ISSUE TITLE
I change English style of this font but Urdu font words change to separate automatically anybody plz give me solution???

### ISSUE THREAD

**Issue by 787Faisal** [googlefonts/Gulzar#105]
![Screenshot_2023-03-06-23-49-51-795_com skaldebane fontviewer-edit](https://user-images.githubusercontent.com/123766496/223729241-591fdf62-0b05-4317-901b-4c4eae177ec3.jpg)

**Comment by simoncozens** [comment]
What do you mean by "change English style of this font"? Is this on a web site or a document? Can you tell me exactly what you have done to make this happen?

**Comment by 787Faisal** [comment]
Dear i want to add roboto font in it for english, i have been tried successfully but when i apply on mobile the urdu words (As shown in the screenshot) have become separate automatically , plz tell any solution

**Comment by simoncozens** [comment]
I think the software you used to change the glyphs to Roboto has removed the features which make the Urdu text work. This isn't something we support.

**Comment by 787Faisal** [comment]
I use font creater, but plz you suggest me how to do this??

**Comment by alerque** [comment]
You can't build fonts like this using generic tooling, you need to use the original build systems.

That being said I'm pretty sure you're going down the wrong path. You said this is for a website. In that case don't worry about changing the font. Use CSS character-ranges to apply different fonts to the English character range. That way you can use Gulzar for all Urdu text but have English text set in a different font in the same content with no markup changes.

**Comment by simoncozens** [comment]
>  plz you suggest me how to do this?

To be honest, I don't suggest you do this...
