### ISSUE TITLE
WHO to see about new Languages? Eg Ancient Egyptian Hieroglyphics and Ancient Egyptian Hieratics

### ISSUE THREAD

**Issue by Nostradamus888** [googlefonts/Gulzar#127]
Hello,
Who should I contact about ideas for a new font system which might be called magno-font ?
This new font system should have a legacy backup
System to make it backwards compatible with older
Operating systems and different cross-platform OS’s.
I only have lots of ideas and little to no programming experience. a tiny bit of Delphi 11 on MS Windows 10 pro.

The new font system would bring to life
the dead language systems of Ancient Egyptian Hieroglyphics and Ancient Egyptian Hieratics.

I know about jsesh.
But, we need to evolve into a more ‘plastic’ 
System that is reflective of social norms.
And offers the possibility of re-emergence of Cultural Laws that reflect a deeper connection with the Divine. Learn to be At-One with all creation.
Glorify Beauty.

Richard

**Comment by simoncozens** [comment]
Not me, I'm afraid - this is a repository about one particular Urdu font.
