### ISSUE TITLE
Dots collision problem 

### ISSUE THREAD

**Issue by Zishan-Nasar** [googlefonts/Gulzar#48]
![mehr vs gulzar](https://user-images.githubusercontent.com/25931391/175016887-9377ff72-3d26-4ccb-b845-976412cfa4f4.png)

**Comment by simoncozens** [comment]
Some of these are reproducible but some are not; can you tell me what environment (editor, OS, version) you are using?

**Comment by simoncozens** [comment]
I think you may have taken an old version of the font. First line is working as designed:
![shape](https://user-images.githubusercontent.com/106728/175657657-9334ed57-c5c3-456e-9505-ee0a7dc239d6.png)

Second line has some clashes:
![shape](https://user-images.githubusercontent.com/106728/175658089-6202374c-9bab-4ceb-b9c8-091f8282f28b.png)

The dots in حنقی are a little close; I will get those fixed.

By the way, what does " جپچا ییییا" mean? My Urdu is not so good.

**Comment by Zishan-Nasar** [comment]
these words are not a proper words. I was just testing the font logics about dots collision. because I applied same tests on my font mehr Nastaliq web. 
one major issues with the gulzar font is that it glyphs shapes are not according to traditional or classical Urdu calligraphy and typography. so it will not get much attraction from Urdu lovers. you should choose a Pakistani calligraphy designer for designing glyphs shapes. because Pakistani Nastaliq and irani Nastaliq are much different from each other in shape and in joining rules as well. I think this is very important point. I am working on Urdu Nastaliq fonts from last 15 years. I had developed a dozen of classical Urdu Nastaliq fonts following the calligraphy of my father.
moreover its rendering speed is too slow due to plenty of GPOS kerning tabels.
overall it is good and much appreciatabel effort by Gulzar team.
I offer my service in order to fix these bugs.

**Comment by simoncozens** [comment]
It's OK, I've fixed the clashes. As far as the design goes, I think we will take our chances.

**Comment by simoncozens** [comment]
Fixed it! Thank you for the report.
![shape](https://user-images.githubusercontent.com/106728/175698636-e1087f1e-7ae9-4b1e-bb84-becfcd17c70a.png)

**Comment by BornaIz** [comment]
> these words are not a proper words. I was just testing the font logics about dots collision. because I applied same tests on my font mehr Nastaliq web. one major issues with the gulzar font is that it glyphs shapes are not according to traditional or classical Urdu calligraphy and typography. so it will not get much attraction from Urdu lovers. you should choose a Pakistani calligraphy designer for designing glyphs shapes. because Pakistani Nastaliq and irani Nastaliq are much different from each other in shape and in joining rules as well. I think this is very important point. I am working on Urdu Nastaliq fonts from last 15 years. I had developed a dozen of classical Urdu Nastaliq fonts following the calligraphy of my father. moreover its rendering speed is too slow due to plenty of GPOS kerning tabels. overall it is good and much appreciatabel effort by Gulzar team. I offer my service in order to fix these bugs.

@Zishan-Nasar Thank you for showing interest in our project. 
Mehr Nastaliq Web is great, and I admire your work. Gulzar is our modest contribution to Urdu typography and we have done our best to base it on appropriate models. However, our approach is more typographic than calligraphic, and we did not intend to directly copy calligraphic models. We are fully aware of regional/linguistic variations of the Nastaliq style that you have mentioned, and this has been reflected in our design. Please do not think of Gulzar as competition for your excellent work but as a different approach to the design and production of an Urdu Nastaliq typeface. Hopefully, our collective effort will provide more powerful tools to further enrich Urdu typography.

**Comment by Zishan-Nasar** [comment]
Muhammad Zeeshan Nasar
Calligrapher | Font Developer | Graphic Designer
Cell No: 0305-6038860
Whats app: +92 305 6038860
Web Site: http://mehrtype.com/
Face Book: https://www.facebook.com/mzishannasar
