### ISSUE TITLE
Dot positioning and collision issues

### ISSUE THREAD

**Issue by saadatm** [googlefonts/Gulzar#49]
Dot positioning and collision bugs that I observed in the Urdu translation of Gulzar's website (in Firefox 101.0.1 on a Windows 10 machine). I used the version of Gulzar that was generated in [this GitHub Action run](https://github.com/googlefonts/Gulzar/actions/runs/2558454825).

| String | Screenshot | Comment |
| --- | --- | --- |
| تقریباً | ![image](https://user-images.githubusercontent.com/6615143/176126516-7dd5b219-0d0f-46aa-a383-508e41b994e5.png) | This word is also used in [one](https://github.com/googlefonts/Gulzar/blob/79c98f610f4648ca52bd0f59ce2c752c487c1add/documentation/promo/Gulzar%20Banner_1.jpg) of the promo images (which are _gorgeous_, by the way). However, in that image, there is no collision among the dots, so not sure what's happening. Perhaps, the font version which was used to create the image did not have the collision, but it later regressed?
| کو بخوبی | ![image](https://user-images.githubusercontent.com/6615143/176126681-e281bd99-89ef-406f-84c4-46a46b12127b.png) | **Fixed** (tested with the font built after https://github.com/googlefonts/Gulzar/commit/f09210d08fbff35b45ef499a306feba05feba711) |
| اب بھی | ![image](https://user-images.githubusercontent.com/6615143/176126757-bf55f10e-496b-41c6-a926-fe5470d81a40.png) | The dot for ب in بھی is usually well-behaved at other places, but in this particular sequence, it is too close to the ب in اب. <br><br>**Fixed** (tested with the font built after https://github.com/googlefonts/Gulzar/commit/f09210d08fbff35b45ef499a306feba05feba711) |
| سمپکنز کمبینیشنز ایپلکیشنز سبز | ![image](https://user-images.githubusercontent.com/6615143/176126917-21aa1c9d-9fd8-4f02-b3bf-4a3e72e07b9f.png) ![image](https://user-images.githubusercontent.com/6615143/176127004-3bd55f73-da3c-47fc-9157-edc33a2032fc.png) ![image](https://user-images.githubusercontent.com/6615143/176127084-58d45a3f-354f-4c37-bfba-b05a13ce617a.png) ![image](https://user-images.githubusercontent.com/6615143/176127172-f7df3dc4-9f4c-4987-9302-31c396b24278.png) | Dot of ز is too far way and sometimes collides with subsequent words. (The first three words are transliterations, but سبز is Urdu for _green_ and I actually used a synonym (ہرا/ہرے) in the translation to avoid having the dot of ز in سبز collide with the next word.) Generally, some sequences that end with نز or بز disturb the dots, like خنز طنز سبز. Same with sequences ending with نڑ, where the dot of ن and small ط of ڑ seem to be flying away. Also note the collision of ا and dots of ے in ایپلیکیشنز, and the cluster of dots when ایپلیکیشنز is followed by بھی. |
| زیرِ | ![image](https://user-images.githubusercontent.com/6615143/176128373-27853262-06ec-419c-9993-23c0e16d0aa3.png) | The _kasra_ is colliding with dots of ی. |
| نئی نئے | ![image](https://user-images.githubusercontent.com/6615143/176128540-9b86ca96-7729-466f-bc77-02ff6498e901.png) ![image](https://user-images.githubusercontent.com/6615143/176128479-c364fda3-9e37-4ba0-9058-d9405eb81527.png) | Dot of ن is too far up. It should be closer to its base, and the mark of _hamza_ may be moved up instead. |
| پیوستہ | ![image](https://user-images.githubusercontent.com/6615143/176128820-2c789fa9-3e57-413a-9782-220e035e728b.png) ![image](https://user-images.githubusercontent.com/6615143/176128865-e95c6fdb-4bc2-43d8-ace6-bd8f8374eed1.png) | Not sure what's hppening here. It appears fine at one place, but at another place its dots are colliding. (Even when there is no collision, it will look better if the dots of ی are moved towards up-left.) |
| نتیجہ | ![image](https://user-images.githubusercontent.com/6615143/176129584-a9cd8176-514d-46de-a194-263a4e718ea4.png) | This isn't bad, but will look better if the dot of ن could be brought closer to its base. |

**Comment by saadatm** [comment]
> I suspect this was caused by https://github.com/googlefonts/Gulzar/commit/79c98f610f4648ca52bd0f59ce2c752c487c1add. I'll see if we can find a happy medium.

This issue is also reproducible with the version of Gulzar currently being used for the website, so its cause is probably older than that commit.

**Comment by saadatm** [comment]
> Not sure what's hppening here. It appears fine at one place, but at another place its dots are colliding. (Even when there is no collision, it will look better if the dots of ی are moved towards up-left.)

Found some more info: Dot collision happens if پیو is preceded by any of د ر و or ہ. Screenshot below:

![paiwasta](https://user-images.githubusercontent.com/6615143/176865957-b67a372d-70f6-4a87-9316-329718c9c52a.png)

**Comment by saadatm** [comment]
After the recent round of bug squashing by @simoncozens, I was curious to see if it also affected any of the problems reported in this issue. `کو بخوبی` and `اب بھی` are now fixed. 👍

![Screenshot 2022-11-10 at 09-48-22 گُلزار نستعلیق اُردو فونٹ](https://user-images.githubusercontent.com/6615143/201004053-3b959118-edc6-4887-9ef2-dffc520af4e2.png)

![Screenshot 2022-11-10 at 09-49-02 گُلزار نستعلیق اُردو فونٹ](https://user-images.githubusercontent.com/6615143/201004071-9a53de03-d2f5-4faa-a213-0051eda2ea20.png)

**Comment by simoncozens** [comment]
Very nice!

**Comment by dboyk** [comment]
Very excited for your work! I’m encountering some dot positioning and collision issues when `ز` is preceded by `ب`, `ن`, or `ہ`. Here are some examples (some are real Urdu words, some not):
<img width="110" alt="Screen Shot 2022-11-28 at 9 55 17 AM" src="https://user-images.githubusercontent.com/62849203/204326177-60317d68-8d56-41ab-b739-5299f9253205.png">
<img width="110" alt="Screen Shot 2022-11-28 at 9 55 29 AM" src="https://user-images.githubusercontent.com/62849203/204326179-af51d154-0b10-407e-aff0-b4a6c49fff0c.png">
<img width="138" alt="Screen Shot 2022-11-28 at 9 55 36 AM" src="https://user-images.githubusercontent.com/62849203/204326181-f7407e80-09e5-4acc-bd13-c66531c57f1b.png">
<img width="138" alt="Screen Shot 2022-11-28 at 9 55 42 AM" src="https://user-images.githubusercontent.com/62849203/204326184-380aa0ed-c346-4e50-850c-77a8121e9a3a.png">
<img width="138" alt="Screen Shot 2022-11-28 at 9 58 50 AM" src="https://user-images.githubusercontent.com/62849203/204326186-df5604a9-dcef-4b38-b297-147e90d9e28b.png">
<img width="138" alt="Screen Shot 2022-11-28 at 9 58 55 AM" src="https://user-images.githubusercontent.com/62849203/204326188-a91a8534-ed47-4808-9c2b-edc95382c1f3.png">
<img width="138" alt="Screen Shot 2022-11-28 at 9 59 31 AM" src="https://user-images.githubusercontent.com/62849203/204326189-ca0e7e31-8bf5-48b5-bc81-def97191428e.png">
<img width="138" alt="Screen Shot 2022-11-28 at 9 59 50 AM" src="https://user-images.githubusercontent.com/62849203/204326190-61233506-3da6-4a53-b252-7a863993b6c6.png">
<img width="138" alt="Screen Shot 2022-11-28 at 9 59 54 AM" src="https://user-images.githubusercontent.com/62849203/204326192-182143e1-7a7a-4a0a-a50a-fcf64c520ca6.png">
<img width="138" alt="Screen Shot 2022-11-28 at 10 08 29 AM" src="https://user-images.githubusercontent.com/62849203/204326194-5ff4bd77-ef8b-4354-bd8c-89ffbf6bb8f5.png">
<img width="138" alt="Screen Shot 2022-11-28 at 10 08 33 AM" src="https://user-images.githubusercontent.com/62849203/204326195-47d42fe4-650d-4099-bd69-20ff55a7ed0c.png">
<img width="138" alt="Screen Shot 2022-11-28 at 10 08 33 AM" src="https://user-images.githubusercontent.com/62849203/204328495-c57259b9-75c4-42fc-8299-deaab37c0b41.png">
<img width="138" alt="Screen Shot 2022-11-28 at 10 20 39 AM" src="https://user-images.githubusercontent.com/62849203/204328457-ec9e9cd5-3be4-4b20-b931-b4f8dceb2413.png">

**Comment by dboyk** [comment]
Quick followup – `ڑ` seems to have the same issues:
<img width="138" alt="Screen Shot 2022-11-28 at 12 35 18 PM" src="https://user-images.githubusercontent.com/62849203/204354355-1291ec3e-082a-489c-80c9-c4f61df34848.png">
<img width="138" alt="Screen Shot 2022-11-28 at 12 35 14 PM" src="https://user-images.githubusercontent.com/62849203/204354369-56028005-f159-4664-9e28-1ffb8bba81e4.png">
