### ISSUE TITLE
Initial shape of ب and similar characters in some sequences

### ISSUE THREAD

**Issue by saadatm** [googlefonts/Gulzar#51]
In the Urdu translation of Gulzar's website, the initial shape of پ and ی in sequences پیٹر and ینٹر (in words پیٹرک and اینٹری, respectively) is a bit odd. Below is a comparison of Gulzar and Noto Nastaliq Urdu:

![image](https://user-images.githubusercontent.com/6615143/176131113-64ded6e9-1cfe-4d3c-83d9-2a2f6a084968.png)

Note how, in Noto, the initial tooth is rounded and short, while in Gulzar it's straighter and longer.

The words above are transliterations, but the issue can also be observed in Urdu words like تیتر بٹیر پنیر etc:

![image](https://user-images.githubusercontent.com/6615143/176131320-0e460034-6ff4-44da-a093-495090efae79.png)

**Comment by BornaIz** [comment]
Thank you so much, Saadat. 
@simoncozens I have just added BEmsd13 + TEmsd13
In such sequences that Saadat has highlighted, we should use from left to right BEi3/TEi3 > BEmsd13/TEmsd13 > BEm16/TEm16 > REf3

**Comment by simoncozens** [comment]
Just to check, is BEmsd13 *only* to be used in BEi/BEm/BEm/REf sequences, or always when following BEm16?
