### ISSUE TITLE
Bari ye + hamzah?

### ISSUE THREAD

**Issue by bgo-eiu** [googlefonts/Gulzar#56]
I just noticed this occurs on ہوۓ for example، the bari ye disappears when it has hamzah:

![image](https://user-images.githubusercontent.com/100172442/190531526-b844bd48-4dd6-4bde-b3fa-62c46b89f6b2.png)

Various platforms have normalizing rules implemented which convert the separate attaching hamzah character + bari ye to the precomposed glyph, preventing that as a workaround.

**Comment by bgo-eiu** [comment]
![image](https://user-images.githubusercontent.com/100172442/190531742-80fff821-6259-4c48-bf03-7ccbcb498425.png)

Using the attaching hamzah does work in the Windows font tester, but if I want to use Gulzar on Urdu Wikipedia for example, inputting it this way is not an option.

**Comment by simoncozens** [comment]
Oh, urgh, that's a missing decomposition rule. I'll fix that.
