### ISSUE TITLE
Adding a letter ڭ (U+06AD) and ە (U+06D5)

### ISSUE THREAD

**Issue by IlyasTarpan** [googlefonts/Gulzar#60]
Good afternoon! Many, many thanks for the masterpiece that you have created! Gulzar is the most beautiful nastaliq font I have ever seen.
I am a native speaker of the Crimean Tatar language, and I want to use Gulzar, because the Crimean Tatars have been using nastaliq for centuries. However, Gulzar does not contain two Crimean Tatar letters - ڭ (U+06AD) and ە (U+06D5).
Letter ڭ  (U+06AD) should look like this:
![Снимок экрана (1497)](https://user-images.githubusercontent.com/113206717/192583190-e049def8-0891-431e-866f-86204ae46cf0.png)
![Снимок экрана (1500)](https://user-images.githubusercontent.com/113206717/192583200-33a63f1f-2545-4218-92fd-77f5eddf983c.png)
![Снимок экрана (1502)](https://user-images.githubusercontent.com/113206717/192583211-455fa3c1-562a-4b16-ad06-b1abd4c6c22e.png)

 Letter ە (U+06D5) is just a modification of the Arabic ه (U+0647), and its only difference is that it does not combine with subsequent letters. It is should look like this:
![Снимок экрана (1503)](https://user-images.githubusercontent.com/113206717/192583260-11271dca-21a0-451d-8e51-cd16477f1415.png)
![Снимок экрана (1505)](https://user-images.githubusercontent.com/113206717/192583286-2b1b15ed-d502-49fa-a69d-810825025a1e.png)
![Снимок экрана (1506)](https://user-images.githubusercontent.com/113206717/192583372-7e5cebfe-eae7-4649-81b7-a66d0ad608cc.png)
![Снимок экрана (1507)](https://user-images.githubusercontent.com/113206717/192583707-16b2d388-e921-4c0e-86f9-5a742be569e4.png)
![Снимок экрана (1509)](https://user-images.githubusercontent.com/113206717/192584452-46fb807e-9493-4dc4-adf9-4d78a67758f5.png)
![Снимок экрана (1510)](https://user-images.githubusercontent.com/113206717/192584482-d348c34f-28d9-448c-bc66-027fa2b2a7d0.png)

**Comment by simoncozens** [comment]
Hello Ilyas, thank you for the kind words! I've added the codepoints you asked for and a few more. Here is some Uyghur text with the new glyphs:

![shape](https://user-images.githubusercontent.com/106728/192632616-2993ed32-0623-49d0-8662-29ffd01d1357.png)

This is available in the repository immediately. I will address a few more issues before making a new release for the Gulzar website and Google Fonts.

**Comment by IlyasTarpan** [comment]
Thank you! It works). May I ask you, is such a form of the letter kaf "permissible" in nastaliq in general?
![Снимок экрана (1519)](https://user-images.githubusercontent.com/113206717/192846124-eb58351a-2b43-41d6-a81f-32e7e8179d8c.png)

**Comment by simoncozens** [comment]
I don’t know! @BornaIz?
