### ISSUE TITLE
Elongated form of be and similar characters not appearing in two-lettered sequences

### ISSUE THREAD

**Issue by saadatm** [googlefonts/Gulzar#62]
When using the `swsh` feature in two-lettered sequences, elongated form of final _be_ (and other _be_-like characters) does not appear if the first letter is:

1. also a _be_ or _be_-like character,
2. _nun_, or
3. _ye_

```
hb-view --features="swsh" -o be-swsh.png Gulzar-Regular.ttf "بت نپ یب"
```
![be-swsh](https://user-images.githubusercontent.com/6615143/195405144-1a2655a3-37b1-4cb7-a429-5f531f0f98da.png)

In sequences with three or more letters, the elongated form appears as expected (albeit with a joining issue as detailed in #61):

```
hb-view --features="swsh" -o be-swsh-2.png Gulzar-Regular.ttf "ثبت پنپ سیب"
```
![be-swsh-2](https://user-images.githubusercontent.com/6615143/195405239-78218c85-b764-4ee4-b7c6-e262fe130357.png)

**Comment by saadatm** [comment]
Thanks for the quick fix, @simoncozens! However, to my eye, `BEisd1` is sitting a bit lower than usual (see the red arrow; green arrow shows the join in `ببت` for comparison):

![bete-bebete](https://user-images.githubusercontent.com/6615143/195767196-9bbf146b-4b68-42a5-886a-75f2f6553b44.png)

Here's how I would adjust it (see the blue arrow):

![bete-bebete-edit](https://user-images.githubusercontent.com/6615143/195767243-9652e055-0c94-4172-8394-93713aa285ec.png)

The sharp point at the start of `TEfs2` may also be reviewed, which IMO clashes with the rest of the joins in the design; @BornaIz can better comment on it, though:

![sharp-entry-point](https://user-images.githubusercontent.com/6615143/195767275-ec033e16-9b68-40b8-985f-073cd8beda62.png)

**Comment by simoncozens** [comment]
Looks like these also need new connection rules.

**Comment by simoncozens** [comment]
@BornaIz, what should be the correct connections between BEfs1 (or BEfs2) and BEi? Also, I have a feeling we are not currently using BEfs2/TEfs2 correctly.

**Comment by BornaIz** [comment]
Thank you, Simon! You're quicker than me, as usual!
