### ISSUE TITLE
Choti yeh + reh + choti yeh dot collision

### ISSUE THREAD

**Issue by bgo-eiu** [googlefonts/Gulzar#64]
Example of پیریں (form of "feet" in Punjabi)

![IMG_20221017_043245](https://user-images.githubusercontent.com/100172442/196130027-3b1cefc1-fdec-4aa6-8022-13500a21f08b.jpg)

**Comment by simoncozens** [comment]
Now:
![shape](https://user-images.githubusercontent.com/106728/200871940-1523a88d-614c-4ab9-be68-6e141ce730bb.png)
