### ISSUE TITLE
Arnun + gaf collision

### ISSUE THREAD

**Issue by bgo-eiu** [googlefonts/Gulzar#65]
Example of a Punjabi word, وݨگی (meaning example or illustration)

![IMG_20221017_121827](https://user-images.githubusercontent.com/100172442/196231990-6a7d8dcc-5a66-42a5-b6ae-45926b928282.jpg)

Maybe the small high tah could be bumped above gaf?

**Comment by simoncozens** [comment]
Now looks like this:
![shape](https://user-images.githubusercontent.com/106728/196268537-d9941503-52fa-47f9-aa3c-8c327c07b08b.png)

Thanks for the report!
