### ISSUE TITLE
Nun + nun + gaf collision

### ISSUE THREAD

**Issue by bgo-eiu** [googlefonts/Gulzar#66]
The fix for the arnun gaf collision is very much appreciated. I spotted another gaf collision with plain nun + plain nun + gaf. This word is ننگے , the plural masculine form of the adjective meaning "naked" in Punjabi.

![image](https://user-images.githubusercontent.com/100172442/197295684-ac8fcbd7-ab0c-465f-b917-61d61a51912f.png)

I noticed that it does not look like this on the version of the font on the Gulzar website

**Comment by simoncozens** [comment]
Yes, this appears to be fixed. I'll update Google Fonts with the latest version
