### ISSUE TITLE
Tteh + cheem + kaf collision

### ISSUE THREAD

**Issue by bgo-eiu** [googlefonts/Gulzar#67]
Sorry to be opening so many of these, but for the sake of documenting them as I notice them -
This word is ٹچکر meaning "joke" or "jest" in Punjabi, or it can be used as a word for the sound made by the sequence "ٹچ" / "Tch" itself.

![image](https://user-images.githubusercontent.com/100172442/197296051-549ae49d-0435-4c14-8ae8-aea84145cfdd.png)

**Comment by simoncozens** [comment]
I've gone with this solution because I didn't like the idea of putting above the kaf head; it felt too disconnected from the BE.
![shape](https://user-images.githubusercontent.com/106728/200875321-064b4bf9-bd42-40dd-9baf-36041c958e5f.png)
