### ISSUE TITLE
zeh + meem + choti yeh collision

### ISSUE THREAD

**Issue by bgo-eiu** [googlefonts/Gulzar#70]
This word is زمزمی an Urdu adjective pertaining to song or chanting
![IMG_20221101_222450](https://user-images.githubusercontent.com/100172442/199381018-3650b993-b7c9-4483-835d-9760299edf82.jpg)

**Comment by simoncozens** [comment]
Now: 
![shape](https://user-images.githubusercontent.com/106728/200887516-9ccc0942-f84a-4a38-bf7e-4272d7ebf749.png)
