### ISSUE TITLE
wau + (nun or lam) + do chashme he + (jeem or cheem) + EOW or word final nun collision

### ISSUE THREAD

**Issue by bgo-eiu** [googlefonts/Gulzar#71]
As specific as it is this is a somewhat common letter sequence pattern in Punjabi.

From right to left, پونچھ (paw/claw), پونجھ (verb to wipe, imperative singular/rude form), پونجھݨ (verb to wipe, gerundal form)
![IMG_20221101_225614](https://user-images.githubusercontent.com/100172442/199385675-92491369-d4da-498d-b771-292f56606680.jpg)

This also occurs with lam following wau in this position as it forms a similar ligature to nun, though this sequence is rather rare by comparison. In ولچھݨ (verb to invert/reverse, gerundal form):
![IMG_20221101_225816](https://user-images.githubusercontent.com/100172442/199386179-527349fb-db10-48b4-8ead-d5c3f8c47612.jpg)

**Comment by simoncozens** [comment]
![shape](https://user-images.githubusercontent.com/106728/200891620-2516b65a-db03-4355-882d-765efdf8230c.png)
![shape](https://user-images.githubusercontent.com/106728/200891703-e242c3d9-f207-41c2-be86-987d38f48234.png)
