### ISSUE TITLE
ghein + cheem + kaf EOW collision

### ISSUE THREAD

**Issue by bgo-eiu** [googlefonts/Gulzar#72]
This is an alternate spelling of the Punjabi verb کھچک "to get angry" (likely came about because there are other words related to being angry or irate which start with غ)

In conjunctive participle form with ک as word final the ghein dot bumps into the kaf. This could use a little nudge upwards so it looks like it does when followed by ے in the masculine plural perfect participle form shown below it

![IMG_20221104_152411](https://user-images.githubusercontent.com/100172442/200058825-1b5ccea1-4cd6-472c-8aaf-abbeb8e5595b.jpg)

**Comment by simoncozens** [comment]
Now:
![shape](https://user-images.githubusercontent.com/106728/200893273-c9fa99cf-6cd7-4e10-8ec7-b95004abacac.png)
