### ISSUE TITLE
Increased space before sequences starting with KAF or GAF

### ISSUE THREAD

**Issue by saadatm** [googlefonts/Gulzar#73]
In Gulzar v1.001, there is increased space before sequences that start with either ک (U+06A9 ARABIC LETTER KEHEH) or گ (U+06AF ARABIC LETTER GAF). Below is a paragraph from Gulzar's website:

![kaf-gaf-increased-space](https://user-images.githubusercontent.com/6615143/201476512-1841f2fa-7a2d-4d82-b09e-fc8c6df877a4.png)

Same paragraph, but the increased spaces are highlighted:

![kaf-gaf-increased-space-highlighted](https://user-images.githubusercontent.com/6615143/201476608-8e08fed8-b04c-428c-8d92-024eac2a33af.png)

The spacing was much better in v1.000:

![kaf-gaf](https://user-images.githubusercontent.com/6615143/201476632-6afc96b1-a6d5-4163-9e21-fa29ed02ddf0.png)

**Comment by simoncozens** [comment]
Argh, FEZ was being too clever and split off my ignore rule into a separate lookup. I'll fix it.
